%Script to Order transects generated by M1 Code from north to south
%Some manual editing may eb necessary after initail pass

NAME_GRD_transects  = 'Douglas'; 

%Directory where output from M1a is stored
Shoreline_dir=['E:\West_Coast_TWL_Hazards\01_Data\Transects\Shoreline_By_County\Oregon_Shorelines\' NAME_GRD_transects '_Shoreline.shp'];
S = shaperead(Shoreline_dir);
dd=numel(S);

order=[(1:dd)'];
OBJECTID=[];
X1=[];
Y1=[];
X2=[];
Y2=[];

for ii=1:dd;
OBJECTID=[OBJECTID;S(ii).OBJECTID;];
X1=[X1;S(ii).X(1);];
Y1=[Y1;S(ii).Y(1);];
X2=[X2;S(ii).X(end-1);];
Y2=[Y2;S(ii).Y(end-1);];
end


table=[order OBJECTID X1 Y1 X2 Y2];

table=sortrows(table,-4);


%from here, know what is the most northern part, so want to
%grab the end and find the next in sequence (basically a nearest neighbor
%analysis)

table2=table;

PathX=S(table2(1,1)).X;
PathY=S(table2(1,1)).Y;
PathX(isnan(PathX))=[];
PathY(isnan(PathY))=[];
table2(1,:)=[];

figure;hold on;plot(PathX,PathY);  
for ii=1:length(table2(:,1));
    
    %1 calculate distance between the end point and the others
    x=PathX(end);
    y=PathY(end);
    
    %for the starts
    xcomp=(x-table2(:,3)).^2;
    ycomp=(y-table2(:,4)).^2;
    
    dstart=sqrt(xcomp+ycomp);
    
    %for the ends
    xcomp=(x-table2(:,5)).^2;
    ycomp=(y-table2(:,6)).^2;
    
    dend=sqrt(xcomp+ycomp);  
    
    [minstart istart]=min(dstart);
    [minend iend]=min(dend);
    
    if minstart<minend;
        index=table2(istart,1);
        table2(istart,:)=[];
        flip=0;
    else
        index=table2(iend,1);
        table2(iend,:)=[];
        flip=1;
    end
    
    if flip == 0;
        PathX=[PathX,S(index).X];
        PathY=[PathY,S(index).Y];
    else
        PathX=[PathX,fliplr(S(index).X)];
        PathY=[PathY,fliplr(S(index).Y)];
    end
PathX(isnan(PathX))=[];
PathY(isnan(PathY))=[];
plot(PathX,PathY);       
end
    
X=PathX;
Y=PathY;
    
X(isnan(X))=[];
Y(isnan(Y))=[];
    
plot(X,Y);       
    
temp.X=X;
temp.Y=Y;
name=[NAME_GRD_transects '_Shoreline'];
eval([name '=temp;']);
save(name,name);
    
    
    
    
    
    
    













